name: HaltLog
version: 1.0
main: com.nzst.haltlog.HaltLogPlugin
api-version: 1.20
commands:
  haltlog:
    description: Hides or restores logs at specified levels
    usage: /haltlog <hide|restore> <1|2|3>
